Add new feature task3
BSYLDRM/Task3A-new pull request #1
Opened 2024-08-02 10:15 UTC by BSYLDRM

feat: add counter fragment with viewmodel
feat: add guess game

2024-08-02 17:11 UTC, TamerSarioglu requested changes
Eline sağlık bir iki refactor önerisi yaptım. Kolay gelsin şimdiden.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/counter/CounterViewModel.kt
> +
class CounterViewModel:ViewModel() {
    private val _counter = MutableLiveData(0)
    val counterNum: LiveData<Int> get() = _counter

    fun incrementCount() {
        _counter.value = _counter.value?.plus(1)
    }
}

refactor edebiliriz bu şekilde. okunması açısından daha kolay.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/game/DetailGameFragment.kt
> +
fazla boşluk var.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/counter/CounterFragment.kt
> +                increaseCounter()
tek satıra indirebiliriz ->  buttonAdd.setOnClickListener { increaseCounter() }

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/counter/CounterFragment.kt
> +    private var checkSwitch = false
boolean değişkenlerde genellikle soru kalıbı gibi bir değişken ismi kullanıyoruz -> "isSwitchChecked" gibi.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/counter/CounterFragment.kt
> +    private fun setObserver() {
viewModel.counterNum.observe(viewLifecycleOwner) { count ->
            if (isSwitchChecked) {
                binding.tvFragmentSay.text = count.toString()
            }
        }
        
        refactor edilebilir.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/counter/CounterFragment.kt
> +    private fun updateTextView() {
binding.tvFragmentSay.text = if (isSwitchChecked) {
            viewModel.counterNum.value?.toString() ?: "0"
        } else {
            counter.toString()
        }
        
        refactor edilebilir.

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/game/GameFragment.kt
> +        outState.putInt("currentGuess", currentGuess ?: -1)
Constant yapabiliriz  -> const val CURRENT_GUESS = "currentGuess"

2024-08-02 17:11 UTC, TamerSarioglu commented on app/src/main/java/com/example/tasks3application/game/SharedVİewModel.kt
> +
fazla boşluk :)

2024-08-02 22:39 UTC, TamerSarioglu requested changes

2024-08-05 08:10 UTC, TamerSarioglu approved these changes
Eline sağlık

2024-08-05 14:01 UTC, kerimisoffline requested changes
Ufak tefek konular var yorum olarak bıraktım. Temiz çalışmışsın, eline sağlık.

2024-08-06 07:16 UTC, merged